def errorfun():
    print("test")
    pass