def errorfunc():
    print("test")
     pass